version: "3.7"
services:
  redis:
    image: redis:latest
    ports:
      - 6380:6379
  app:
    build:
      context: .

    container_name: fastapi_app
    ports:
      - "8001:80"
    depends_on:
      - redis
    command: uvicorn main:app --reload --port 80
networks:
  custom:
    driver: bridge