version: "3.7"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  app:
    build:
      context: .

    container_name: fastapi_app
    ports:
      - "8001:80"
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 80
networks:
  custom:
    driver: bridge